CREATE TABLE lancamento (
    CODIGO BIGINT(20) PRIMARY KEY AUTO_INCREMENT,
    DESCRICAO VARCHAR(50) NOT NULL,
    DATA_VENCIMENTO DATE NOT NULL,
    DATA_PAGAMENTO DATE,
    VALOR DECIMAL(10,2) NOT NULL,
    OBSERVACAO VARCHAR(100),
    TIPO VARCHAR(20) NOT NULL,
    CODIGO_CATEGORIA BIGINT(20) NOT NULL,
    CODIGO_PESSOA BIGINT(20) NOT NULL,
    FOREIGN KEY (CODIGO_CATEGORIA) REFERENCES categoria(CODIGO),
    FOREIGN KEY (CODIGO_PESSOA) REFERENCES pessoa(CODIGO)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(1, 'Crocks Lemoel', '2019-11-04', '2019-11-05', 151.00, 'Americanas', 'DESPESA', 6, 1);

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(2, 'Arroz', '2019-11-04', '2019-11-05', 152.00, 'Americanas', 'RECEITA', 6, 1);

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(3, 'Feijao', '2019-11-04', '2019-11-05', 153.00, 'Americanas', 'DESPESA', 6, 1);

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(4, 'Carne', '2019-11-04', '2019-11-05', 154.00, 'Americanas', 'RECEITA', 6, 1);

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(5, 'Clube', '2019-11-04', '2019-11-05', 155.00, 'Americanas', 'RECEITA', 6, 1);

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(6, 'Praia', '2019-11-04', '2019-11-05', 156.00, 'Americanas', 'DESPESA', 6, 1);

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(7, 'Lapis e Canetas', '2019-11-04', '2019-11-05', 157.00, 'Americanas', 'RECEITA', 6, 1);

INSERT INTO cash.lancamento
(CODIGO, DESCRICAO, DATA_VENCIMENTO, DATA_PAGAMENTO, VALOR, OBSERVACAO, TIPO, CODIGO_CATEGORIA, CODIGO_PESSOA)
VALUES(8, 'Celular', '2019-11-04', '2019-11-05', 158.00, 'Americanas', 'DESPESA', 6, 1);